<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="naveenautomationlabss-MacBook-Pro.local" failures="3" tests="6" name="Surefire test" time="6.166" errors="0" timestamp="2023-04-18T20:50:33 IST">
  <testcase classname="com.qa.api.tests.CreateUserWithJsonFileTest" name="createUserTest" time="0.282">
    <failure type="java.lang.AssertionError" message="expected [201] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [401]
at com.qa.api.tests.CreateUserWithJsonFileTest.createUserTest(CreateUserWithJsonFileTest.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- createUserTest -->
  <testcase classname="com.qa.api.tests.CreateUserTestWithJsonStringTest" name="createUserTest" time="0.722"/>
  <testcase classname="com.qa.api.tests.CreateUserPostCallTest" name="createUserTest" time="0.576"/>
  <testcase classname="com.qa.api.tests.APIResponseHeadersTest" name="getHeadersTest" time="0.291"/>
  <testcase classname="com.qa.api.tests.APIDisposeTest" name="disposeResponseTest" time="0.459">
    <failure type="com.microsoft.playwright.PlaywrightException" message="Response has been disposed">
      <![CDATA[com.microsoft.playwright.PlaywrightException: Response has been disposed
at com.microsoft.playwright.impl.APIResponseImpl.lambda$body$0(APIResponseImpl.java:55)
at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:87)
at com.microsoft.playwright.impl.APIResponseImpl.body(APIResponseImpl.java:49)
at com.microsoft.playwright.impl.APIResponseImpl.text(APIResponseImpl.java:104)
at com.qa.api.tests.APIDisposeTest.disposeResponseTest(APIDisposeTest.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- disposeResponseTest -->
  <testcase classname="com.qa.api.tests.CreateUserWithPOJOTest" name="createUserTest" time="0.216">
    <failure type="java.lang.AssertionError" message="expected [201] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [401]
at com.qa.api.tests.CreateUserWithPOJOTest.createUserTest(CreateUserWithPOJOTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- createUserTest -->
</testsuite> <!-- Surefire test -->
